import type { Metadata } from "next";
import { Geist, Geist_Mono, Prompt } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ToastContainer } from "@/components/ui/toast-container";

const prompt = Prompt({ subsets: ['thai'], weight: ['400', '600', '700'] });
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Audit System",
  description: "Generated by audit system",
  icons: { icon: "/logo.svg" },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${prompt.className} antialiased`}>
        {children}
        <Toaster />
        <ToastContainer />
      </body>
    </html>
  );
}
